<?php

namespace AppBundle\Repository;

/**
 * SquadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SquadRepository extends \Doctrine\ORM\EntityRepository
{
}
